In [1]:
#QUESTION 1

In [2]:
import numpy as np

In [3]:
arr=np.array([[8,9,10],[11,12,13]])
print(arr)

[[ 8  9 10]
 [11 12 13]]


In [4]:
arr.reshape(3,2)

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [5]:
#QUESTION 2

In [6]:
array=np.array([[8,9],[10,11],[12,13]])

print(array)

[[ 8  9]
 [10 11]
 [12 13]]


In [7]:
array.reshape(1,6)

array([[ 8,  9, 10, 11, 12, 13]])

In [11]:
array[1]

array([10, 11])